### ISSUE TITLE
Combobox example in demo

### ISSUE THREAD

**Issue by Symbai** [SeriousM/WPFLocalizationExtension#129]
Hi,

I'm trying to add localization of comboitems and looked at the demo. But if I change the language the demo app is always displaying "Key:Monday". The days are not translated. Did I missed something or is there any practical example for a combobox?

**Comment by nzain** [comment]
The wiki at
https://github.com/SeriousM/WPFLocalizationExtension/wiki/LocProxy-&-EnumComboBox
says (regarding EnumComboBox)
> A complete example is included in the AssemblyTest example located in the source code of the library.

**Comment by Symbai** [comment]
Did you tried the example (read my post)? Because that's what i am talking about. The example that should demonstrate the EnumComboBox doesn't work on my end, the items are not translated.

**Comment by SeriousM** [comment]
Hi @Symbai, could you please provide a small working example so we can help you?

"...doesn't work on my end..." isn't very helpful.

**Comment by Symbai** [comment]
I'm sorry. I would upload an example but is your example application right in your github repo so all you need is to download it and run it. Please see the GIF perhaps it more clear then:

![untitled project](https://user-images.githubusercontent.com/14368203/34696478-4a016ae2-f4cf-11e7-9836-4dcaef89531b.gif)

(As you might see, everything is translated except the combobox items.)

**Comment by adragoner** [comment]
Hi @Symbai,

It seems that WPFLocalizationExtensionDemoApplication was not finished. Please use AssemblyTest example as suggested by @nzain.

@SeriousM, shall we consider removing this demo project from the repository?

**Comment by Symbai** [comment]
Ok found it. I clicked on the demo here and there (don't actually remember the exact steps) and an exception was thrown. Just in case it helps:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WPFLocalizeExtension
  StackTrace:
   at WPFLocalizeExtension.Providers.ResxLocalizationProviderBase.GetLocalizedObject(String key, DependencyObject target, CultureInfo culture) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Providers\ResxLocalizationProviderBase.cs:line 632
   at WPFLocalizeExtension.Engine.LocalizeDictionary.GetLocalizedObject(String key, DependencyObject target, CultureInfo culture, ILocalizationProvider provider) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Engine\LocalizeDictionary.cs:line 822
   at WPFLocalizeExtension.Engine.LocalizeDictionary.GetLocalizedObject(String key, DependencyObject target, CultureInfo culture) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Engine\LocalizeDictionary.cs:line 806
   at WPFLocalizeExtension.Extensions.LocExtension.FormatOutput(TargetInfo endPoint, TargetInfo info) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Extensions\LocExtension.cs:line 512
   at WPFLocalizeExtension.Extensions.LocTextExtension.FormatOutput(TargetInfo endPoint, TargetInfo info) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Extensions\Compatibility.cs:line 222
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue()
   at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Extensions\LocExtension.cs:line 301
   at WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Engine\LocalizeDictionary.cs:line 1002
   at WPFLocalizeExtension.Engine.LocalizeDictionary.set_Culture(CultureInfo value) in C:\Joses\Jose\Desktop\WPFLocalizationExtension-master\WPFLocalizeExtension\Engine\LocalizeDictionary.cs:line 629

```

**Comment by xmedeko** [comment]
Seems like a bug coming from #128 that empty keys leads to such problems. Have to fix that.

**Comment by xmedeko** [comment]
@SeriousM I have added a commit fixing the NRE.
I've also fixed the combobx resources in the PR, see #130. If you want to remove the DemoApplication, then just close the PR without merging.

**Comment by Symbai** [comment]
No I didn't changed anything. After adragoner was letting me know about Im using the wrong demo Ive just downloaded the recent source code and run it with VS 2017. After receiving the exception i couldnt reproduce it but like I said, I cannot remember the order I've clicked on all buttons when exception was thrown.

**Comment by xmedeko** [comment]
OK, I've moved the conversation to the #130, so closing this issue.
